<?php
require __DIR__.'/includes/bootstrap.php';
$cart=cart_items();
if(!$cart){ redirect_to(base_url('cart.php')); }
$items=[];$subtotal=0;
foreach($cart as $item){$line=(float)$item['unit_price']*(float)$item['quantity'];$item['line_total']=$line;$item['item_discount']=anniversary_discount((float)$item['quantity'],(float)$item['unit_price']);$item['net_total']=max(0,$line-$item['item_discount']);$subtotal+=$line;$items[]=$item;}
$discount=cart_discount($cart);$total=max(0,$subtotal-$discount);
$pageTitle='Checkout';$active='fabrics';require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="max-w-7xl mx-auto px-4 py-14"><span>SECURE CHECKOUT</span><h1>Complete your order</h1><p>Enter your delivery details and continue to secure Paystack payment.</p></div></section>
<section class="max-w-7xl mx-auto px-4 py-12"><form id="checkoutForm" class="grid lg:grid-cols-[1fr_390px] gap-8 items-start">
<div class="bg-white border rounded-3xl p-6 sm:p-8"><h2 class="text-2xl font-extrabold text-benaki-navy">Customer & delivery details</h2><div class="grid sm:grid-cols-2 gap-5 mt-7"><div><label class="label">Full name *</label><input name="fullname" required maxlength="120" class="input"></div><div><label class="label">Email address *</label><input name="email" type="email" required maxlength="160" class="input"></div><div><label class="label">Phone number *</label><input name="phone" required maxlength="50" class="input"></div><div><label class="label">Location / delivery address *</label><input name="location" required maxlength="200" class="input"></div></div><div class="mt-5"><label class="label">Order note</label><textarea name="description" rows="4" maxlength="3000" class="input" placeholder="Any colour, delivery or tailoring information..."></textarea></div><div class="mt-6 rounded-2xl bg-emerald-50 border border-emerald-100 p-4 text-sm text-emerald-900"><b>Secure payment:</b> Clicking “Pay with Paystack” opens Paystack Checkout. Benaki Fabrics never sees or stores your card details.</div><div id="checkoutResult" class="mt-5 text-sm" aria-live="polite"></div><button id="payBtn" class="mt-5 w-full bg-benaki-gold text-benaki-navy py-4 rounded-xl font-extrabold text-base" type="submit">Pay <?=money($total)?> with Paystack</button></div>
<aside class="bg-benaki-navy text-white rounded-3xl p-6 lg:sticky lg:top-28"><h2 class="text-xl font-extrabold">Your cart</h2><div class="mt-5 space-y-4"><?php foreach($items as $item): ?><div class="flex gap-3"><img src="<?=e(media_url($item['image_path']))?>" class="w-14 h-14 object-cover rounded-lg"><div class="flex-1"><b class="text-sm"><?=e($item['name'])?></b><p class="text-[11px] text-white/60"><?=e((string)$item['quantity'])?> × <?=money((float)$item['unit_price'])?></p><p class="text-[11px] text-white/60"><?=e(implode(', ',$item['colors']))?></p><?php if($item['item_discount']>0): ?><p class="text-[11px] text-amber-300 font-bold">Save <?=money((float)$item['item_discount'])?></p><?php endif; ?></div><div class="text-right"><strong><?=money((float)$item['line_total'])?></strong><?php if($item['item_discount']>0): ?><p class="text-[10px] text-emerald-300 mt-1">Net <?=money((float)$item['net_total'])?></p><?php endif; ?></div></div><?php endforeach; ?></div><div class="border-t border-white/10 mt-6 pt-5 space-y-3 text-sm"><div class="flex justify-between"><span>Subtotal</span><b><?=money($subtotal)?></b></div><div class="flex justify-between"><span>Anniversary savings</span><b class="text-amber-300">-<?=money($discount)?></b></div><p class="text-[11px] text-white/60">Savings are calculated for each cart item and applied to its price.</p><div class="flex justify-between text-xl pt-3 border-t border-white/10"><span>Total</span><b><?=money($total)?></b></div></div></aside>
</form></section>
<script>window.BENAKI_CHECKOUT={endpoint:<?=json_encode(base_url('payment/initialize.php'))?>,verify:<?=json_encode(base_url('payment/verify.php'))?>,receipt:<?=json_encode(base_url('receipt.php'))?>};</script>
<script src="<?=e(base_url('assets/js/checkout.js'))?>"></script>
<?php require __DIR__.'/includes/footer.php'; ?>
