<?php
$config = require __DIR__ . '/config/config.php';
$biz = $config['business'];
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Benaki Fabrics — premium fabrics, quality textiles and dependable supply across South East and South South Nigeria. Celebrating 1 year of quality, service and amazing gifts.">
  <title>Benaki Fabrics | 1 Year Anniversary</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script>tailwind.config={theme:{extend:{colors:{benaki:{navy:'#061b33',gold:'#d89a18',cream:'#fffaf0'}}}}}</script>
  <link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>
<header class="sticky top-0 z-50 bg-white/90 backdrop-blur border-b border-slate-100">
  <div class="max-w-7xl mx-auto px-5 lg:px-8 h-20 flex items-center justify-between">
    <a href="#home" class="flex items-center gap-3">
      <img src="assets/img/benaki-logo.jpg" alt="Benaki Fabrics" class="h-14 w-auto rounded-lg object-cover object-left">
    </a>
    <nav class="hidden md:flex items-center gap-7 text-sm font-semibold text-slate-700">
      <a href="#home" class="hover:text-amber-600">Home</a><a href="#about" class="hover:text-amber-600">About</a><a href="#fabrics" class="hover:text-amber-600">Fabrics</a><a href="#anniversary" class="hover:text-amber-600">Anniversary</a><a href="#contact" class="hover:text-amber-600">Contact</a>
    </nav>
    <button data-order class="btn-gold rounded-full px-5 py-3 text-sm font-bold hidden sm:inline-flex">Order & Get Your Gift</button>
    <button id="navToggle" class="md:hidden rounded-xl p-2 bg-slate-100" aria-label="Open menu">☰</button>
  </div>
  <div id="mobileNav" class="hidden md:hidden px-5 pb-5 border-t border-slate-100 bg-white">
    <div class="grid gap-3 pt-4 text-sm font-semibold"><a href="#home">Home</a><a href="#about">About</a><a href="#fabrics">Fabrics</a><a href="#anniversary">Anniversary</a><a href="#contact">Contact</a><button data-order class="btn-gold rounded-xl px-4 py-3 text-left">Make an Order</button></div>
  </div>
</header>

<main>
<section id="home" class="hero-bg relative overflow-hidden">
  <div class="max-w-7xl mx-auto px-5 lg:px-8 py-16 lg:py-24 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center">
    <div>
      <div class="inline-flex items-center gap-2 rounded-full border border-amber-200 bg-white/80 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-amber-700">Celebrating 1 Year • Calabar</div>
      <h1 class="hero-title mt-6 text-6xl lg:text-8xl font-black tracking-tight text-benaki-navy">Quality fabrics.<br><span class="text-amber-600">Exceptional service.</span></h1>
      <p class="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Benaki Fabrics supplies premium textile materials to customers, designers, tailors and fashion businesses across the South East and South South Nigeria.</p>
      <div class="mt-8 flex flex-wrap gap-3"><button data-order class="btn-gold rounded-full px-7 py-4 font-extrabold">Make an Order & Get Your Amazing Gift →</button><a href="#fabrics" class="btn-dark rounded-full px-7 py-4 font-bold">Explore Fabrics</a></div>
      <div class="mt-9 grid grid-cols-3 gap-3 max-w-xl">
        <div class="glass rounded-2xl p-4"><div class="text-2xl font-black text-benaki-navy">5+</div><div class="text-xs text-slate-500">Fabric categories</div></div>
        <div class="glass rounded-2xl p-4"><div class="text-2xl font-black text-benaki-navy">2</div><div class="text-xs text-slate-500">Delivery regions</div></div>
        <div class="glass rounded-2xl p-4"><div class="text-2xl font-black text-benaki-navy">1 yr</div><div class="text-xs text-slate-500">Serving with love</div></div>
      </div>
    </div>
    <div class="relative">
      <div class="absolute -inset-8 rounded-[40px] bg-amber-200/30 blur-3xl"></div>
      <div class="relative rounded-[32px] overflow-hidden shadow-2xl border-8 border-white"><img src="assets/img/anniversary-source.jpg" alt="Benaki Fabrics 1 year anniversary" class="w-full"></div>
    </div>
  </div>
</section>

<section id="about" class="py-20 lg:py-28 bg-white">
  <div class="max-w-7xl mx-auto px-5 lg:px-8 grid lg:grid-cols-2 gap-12 items-center">
    <div class="grid grid-cols-2 gap-4"><img src="assets/img/fabric-stack.jpg" class="rounded-3xl h-80 w-full object-cover" alt="Stack of quality fabrics"><img src="assets/img/floral-crepe.jpg" class="rounded-3xl h-80 w-full object-cover" alt="Floral fabric"><div class="col-span-2 rounded-3xl bg-benaki-navy text-white p-7"><p class="text-amber-300 font-bold uppercase tracking-widest text-xs">Our promise</p><p class="serif text-2xl mt-2">“Finest quality textiles, delivered with the care your business deserves.”</p></div></div>
    <div><p class="text-sm uppercase tracking-[.22em] font-extrabold text-amber-600">About Benaki Fabrics</p><h2 class="mt-3 text-4xl lg:text-5xl font-black text-benaki-navy">A fabric partner built around quality.</h2><p class="mt-6 text-slate-600 leading-8">From everyday fashion projects to special outfits and bulk supply, Benaki Fabrics is focused on making quality fabrics easier to source. We are based in Calabar and deliver to customers throughout the South East and South South.</p><div class="mt-7 grid sm:grid-cols-2 gap-4"><div class="card p-5"><div class="text-2xl">✦</div><h3 class="font-extrabold mt-2">Trusted quality</h3><p class="text-sm text-slate-500 mt-1">Carefully selected fabrics for beautiful finishing.</p></div><div class="card p-5"><div class="text-2xl">◈</div><h3 class="font-extrabold mt-2">Easy ordering</h3><p class="text-sm text-slate-500 mt-1">Choose your fabric, colour, measurement and quantity.</p></div></div></div>
  </div>
</section>

<section id="fabrics" class="py-20 lg:py-28 bg-slate-50">
  <div class="max-w-7xl mx-auto px-5 lg:px-8"><div class="max-w-2xl"><p class="text-sm uppercase tracking-[.22em] font-extrabold text-amber-600">Our fabrics</p><h2 class="mt-3 text-4xl lg:text-5xl font-black text-benaki-navy">Five quality fabric types.</h2><p class="mt-4 text-slate-600">Pick a fabric type when you place your order and tell us the colours you want.</p></div>
    <div class="mt-10 grid sm:grid-cols-2 lg:grid-cols-5 gap-5">
      <?php $fabricCards=[['Stock','fabric-1.jpg','Versatile, polished and dependable.'],['Jonkoso','fabric-2.jpg','Rich texture for standout looks.'],['Crepe','floral-crepe.jpg','Elegant drape with a premium feel.'],['Vintage','fabric-4.jpg','Classic styling for timeless outfits.'],['Chinos','fabric-5.jpg','Smart, durable and fashion-ready.']]; foreach($fabricCards as $i=>$f): ?>
      <article class="fabric-card"><img src="assets/img/<?= htmlspecialchars($f[1]) ?>" alt="<?= htmlspecialchars($f[0]) ?> fabric"><div class="fabric-info"><p class="text-xs uppercase tracking-widest text-amber-300 font-bold">Fabric <?= $i+1 ?></p><h3 class="text-2xl font-black mt-1"><?= htmlspecialchars($f[0]) ?></h3><p class="text-sm text-white/75 mt-1"><?= htmlspecialchars($f[2]) ?></p></div></article>
      <?php endforeach; ?>
    </div>
  </div>
</section>

<section id="anniversary" class="py-20 lg:py-28 bg-benaki-navy text-white overflow-hidden">
  <div class="max-w-7xl mx-auto px-5 lg:px-8 grid lg:grid-cols-[.9fr_1.1fr] gap-12 items-center"><div><p class="text-sm uppercase tracking-[.22em] text-amber-300 font-extrabold">One year. One big thank you.</p><h2 class="mt-4 text-5xl lg:text-6xl font-black">We are giving you more reasons to <span class="text-amber-300">love quality.</span></h2><p class="mt-6 text-white/70 leading-8">For our anniversary, customers who order from 3 yards and above can enjoy amazing gift opportunities. Place your order today and let us celebrate with you.</p><button data-order class="mt-8 btn-gold rounded-full px-7 py-4 font-extrabold">Get My Amazing Gift →</button></div>
    <div class="grid grid-cols-2 gap-4"><div class="rounded-3xl overflow-hidden border border-white/10"><img src="assets/img/fabric-stack.jpg" class="w-full h-64 object-cover" alt="Premium fabric stack"></div><div class="rounded-3xl bg-white/10 p-7 flex flex-col justify-end"><div class="text-5xl font-black text-amber-300">3+</div><p class="mt-2 font-bold">yards and above</p><p class="mt-1 text-sm text-white/60">eligible for anniversary gift consideration.</p></div><div class="col-span-2 rounded-3xl bg-gradient-to-r from-amber-400 to-yellow-200 text-benaki-navy p-7 flex items-center justify-between gap-6"><div><p class="font-black text-xl">Premium Quality</p><p class="text-sm opacity-75">Exciting gifts • Shop & Save</p></div><div class="text-5xl">🎁</div></div></div>
  </div>
</section>

<section class="py-20 bg-white"><div class="max-w-7xl mx-auto px-5 lg:px-8"><div class="card overflow-hidden bg-gradient-to-r from-[#fffaf0] to-white grid md:grid-cols-[1fr_auto] items-center"><div class="p-8 lg:p-12"><p class="text-amber-700 font-extrabold uppercase tracking-[.18em] text-xs">Anniversary special</p><h2 class="mt-3 text-3xl lg:text-4xl font-black text-benaki-navy">Ready to make your next outfit exceptional?</h2><p class="mt-3 text-slate-600">Tell us what you need. We will calculate your estimated fabric cost instantly.</p></div><div class="p-8 lg:p-12"><button data-order class="btn-gold rounded-full px-8 py-4 font-extrabold whitespace-nowrap">Order Now & Get Your Gift</button></div></div></div></section>

<section id="contact" class="py-20 lg:py-28 bg-slate-50"><div class="max-w-7xl mx-auto px-5 lg:px-8 grid lg:grid-cols-2 gap-12"><div><p class="text-sm uppercase tracking-[.22em] font-extrabold text-amber-600">Contact us</p><h2 class="mt-3 text-4xl lg:text-5xl font-black text-benaki-navy">Let’s talk fabrics.</h2><p class="mt-5 text-slate-600 leading-8">Reach us for availability, colours, bulk supply, delivery questions or any fabric request.</p><div class="mt-8 space-y-4"><a href="tel:<?= $biz['phone1'] ?>" class="card p-5 flex items-center gap-4 hover:-translate-y-1 transition"><span class="w-12 h-12 rounded-2xl bg-benaki-navy text-white grid place-items-center">☎</span><div><p class="text-xs text-slate-500 uppercase tracking-widest">Call / WhatsApp</p><p class="font-extrabold text-lg"><?= $biz['phone1'] ?> • <?= $biz['phone2'] ?></p></div></a><div class="card p-5 flex items-center gap-4"><span class="w-12 h-12 rounded-2xl bg-amber-100 text-amber-700 grid place-items-center">⌖</span><div><p class="text-xs text-slate-500 uppercase tracking-widest">Location</p><p class="font-extrabold text-lg">Calabar</p><p class="text-sm text-slate-500">Delivery: South East / South South</p></div></div></div></div>
  <div class="card p-7 lg:p-9"><div id="contactSuccess" class="hidden mb-5 rounded-2xl bg-emerald-50 text-emerald-800 p-4 font-semibold">Thank you! Your message has been sent successfully.</div><form id="contactForm" class="space-y-5"><div class="grid sm:grid-cols-2 gap-4"><div><label class="text-sm font-bold">Full name</label><input class="input mt-2" name="fullname" required></div><div><label class="text-sm font-bold">Phone</label><input class="input mt-2" name="phone" inputmode="tel" required></div></div><div><label class="text-sm font-bold">Email <span class="font-normal text-slate-400">(optional)</span></label><input class="input mt-2" type="email" name="email"></div><div><label class="text-sm font-bold">Message</label><textarea class="input mt-2" name="message" rows="5" required></textarea></div><input class="hidden" name="website" tabindex="-1" autocomplete="off"><button id="contactSubmit" class="btn-dark rounded-xl px-6 py-3.5 font-extrabold w-full">Send Message</button></form></div>
</div></section>
</main>

<footer class="bg-[#031426] text-white"><div class="max-w-7xl mx-auto px-5 lg:px-8 py-10 flex flex-col md:flex-row gap-5 justify-between items-center"><div><p class="font-black text-xl">BENAKI <span class="text-amber-300">FABRICS</span></p><p class="text-white/50 text-sm mt-1">Finest Quality Textiles • Celebrating 1 Year</p></div><p class="text-white/50 text-sm">© <?= date('Y') ?> Benaki Fabrics. All rights reserved.</p></div></footer>

<!-- Anniversary flyer popup -->
<div id="flyerModal" class="modal" role="dialog" aria-modal="true" aria-label="Benaki Fabrics anniversary flyer"><div class="modal-panel flyer-panel relative"><button data-close="flyerModal" class="absolute -top-3 -right-2 z-10 w-10 h-10 rounded-full bg-white text-slate-800 shadow-xl font-bold">×</button><div class="flyer-design active"><img src="assets/img/anniversary-source.jpg" class="flyer-img" alt="Benaki Fabrics anniversary flyer"></div>
  <div class="flyer-design"><div class="flyer-card dark text-center"><p class="text-amber-300 uppercase tracking-[.3em] font-bold text-xs">Benaki Fabrics</p><div class="text-8xl font-black text-white mt-10">1</div><p class="script text-6xl text-amber-300 -mt-5">Year Anniversary</p><p class="serif text-2xl mt-8">A whole year of quality, colour & style.</p><div class="mt-9 inline-block rounded-full border border-amber-300/50 px-7 py-4"><span class="font-black text-amber-300">ORDER 3+ YARDS</span><br><span class="text-sm text-white/75">and enjoy our anniversary gift offer</span></div><div class="mini-fabrics"><span style="background-image:url('assets/img/fabric-1.jpg')"></span><span style="background-image:url('assets/img/fabric-2.jpg')"></span><span style="background-image:url('assets/img/floral-crepe.jpg')"></span><span style="background-image:url('assets/img/fabric-4.jpg')"></span><span style="background-image:url('assets/img/fabric-5.jpg')"></span></div></div></div>
  <div class="flyer-design"><div class="flyer-card cream"><div class="flex justify-between items-start"><div><p class="font-black text-2xl tracking-tight">BENAKI <span class="text-amber-600">FABRICS</span></p><p class="text-xs text-slate-500">Finest Quality Textiles</p></div><div class="rounded-full bg-benaki-navy text-white w-20 h-20 grid place-items-center font-black text-2xl">1Y</div></div><div class="mt-20"><p class="text-amber-700 font-extrabold uppercase tracking-[.25em] text-sm">Celebrating our</p><h3 class="text-7xl font-black text-benaki-navy leading-none mt-2">1 YEAR</h3><p class="script text-6xl text-amber-600 -mt-1">Anniversary</p><p class="mt-8 max-w-lg text-slate-600 text-lg">Thank you for making Benaki Fabrics part of your fashion journey. Come shop premium fabrics and receive an amazing anniversary gift.</p><button class="mt-8 btn-dark rounded-full px-7 py-3 font-bold">ORDER 3+ YARDS</button></div><div class="mini-fabrics"><span style="background-image:url('assets/img/fabric-5.jpg')"></span><span style="background-image:url('assets/img/floral-crepe.jpg')"></span><span style="background-image:url('assets/img/fabric-1.jpg')"></span><span style="background-image:url('assets/img/fabric-3.jpg')"></span><span style="background-image:url('assets/img/fabric-4.jpg')"></span></div></div></div>
  <div class="flyer-design"><div class="flyer-card dark"><div class="max-w-xl"><div class="flex items-center justify-between"><p class="font-black text-xl">B<span class="text-amber-300">F</span> • BENAKI FABRICS</p><span class="text-amber-300 text-2xl">✦</span></div><p class="mt-20 text-amber-300 font-bold uppercase tracking-[.25em]">One year. One celebration.</p><h3 class="text-6xl font-black mt-3">AMAZING<br><span class="text-amber-300">GIFTS</span></h3><p class="text-white/70 text-lg mt-5">Shop quality fabrics from 3 yards and above and stand a chance to enjoy our anniversary gift offer.</p><div class="mt-8 grid grid-cols-3 gap-3 text-center"><div class="rounded-2xl bg-white/10 p-4"><div class="text-2xl">✦</div><div class="text-xs mt-2">Premium</div></div><div class="rounded-2xl bg-white/10 p-4"><div class="text-2xl">🎁</div><div class="text-xs mt-2">Exciting</div></div><div class="rounded-2xl bg-white/10 p-4"><div class="text-2xl">✓</div><div class="text-xs mt-2">Trusted</div></div></div></div><div class="mini-fabrics"><span style="background-image:url('assets/img/floral-crepe.jpg')"></span><span style="background-image:url('assets/img/fabric-2.jpg')"></span><span style="background-image:url('assets/img/fabric-3.jpg')"></span><span style="background-image:url('assets/img/fabric-4.jpg')"></span><span style="background-image:url('assets/img/fabric-5.jpg')"></span></div></div></div>
  <div class="flyer-design"><div class="flyer-card cream text-center"><p class="text-xs font-black tracking-[.3em] text-amber-700">BENAKI FABRICS PRESENTS</p><div class="mx-auto mt-10 w-32 h-32 rounded-full bg-benaki-navy text-white grid place-items-center border-8 border-amber-300"><span class="text-6xl font-black">1</span></div><h3 class="mt-8 text-5xl font-black text-benaki-navy">QUALITY<br><span class="text-amber-600">WORTH CELEBRATING</span></h3><p class="serif text-2xl mt-4 text-slate-600">Our 1-Year Anniversary</p><p class="max-w-xl mx-auto mt-7 text-slate-600">Celebrate with us and enjoy amazing gifts on eligible fabric orders from 3 yards and above.</p><div class="mt-7 inline-flex items-center gap-2 rounded-full bg-benaki-navy text-white px-6 py-3 font-bold">SHOP • SAVE • CELEBRATE</div><div class="mini-fabrics"><span style="background-image:url('assets/img/fabric-1.jpg')"></span><span style="background-image:url('assets/img/fabric-2.jpg')"></span><span style="background-image:url('assets/img/floral-crepe.jpg')"></span><span style="background-image:url('assets/img/fabric-4.jpg')"></span><span style="background-image:url('assets/img/fabric-5.jpg')"></span></div></div></div>
  <div class="mt-4 flex justify-center gap-2"><button id="nextFlyer" class="rounded-full bg-white px-5 py-2.5 font-bold text-slate-800 shadow-lg">View another design ↻</button><button data-close="flyerModal" class="rounded-full bg-benaki-navy px-5 py-2.5 font-bold text-white shadow-lg">Continue to site</button></div>
</div></div>

<!-- Order modal -->
<div id="orderModal" class="modal" role="dialog" aria-modal="true" aria-label="Order request"><div class="modal-panel"><div class="p-6 lg:p-8 border-b border-slate-100 flex items-center justify-between"><div><p class="text-xs uppercase tracking-[.2em] font-black text-amber-600">1 Year Anniversary</p><h2 class="text-2xl lg:text-3xl font-black text-benaki-navy">Order & Get Your Amazing Gift</h2><p class="text-sm text-slate-500 mt-1">Choose your fabric, colours and quantity. Your estimated total updates instantly.</p></div><button data-close="orderModal" class="w-10 h-10 rounded-full bg-slate-100 font-bold">×</button></div>
<form id="orderForm" class="p-6 lg:p-8"><div class="grid lg:grid-cols-[1.2fr_.8fr] gap-8"><div class="space-y-5"><div><label class="text-sm font-bold">Fabric Type *</label><select id="fabric_type" name="fabric_type" class="input mt-2" required><option value="">Select fabric</option><option>Jonkoso</option><option>Crepe</option><option>Stock</option><option>Vintage</option><option>Chinos</option></select></div>
<div><label class="text-sm font-bold">Colour(s) * <span class="font-normal text-slate-400">Select one or more</span></label><div class="flex flex-wrap gap-2 mt-2"><?php foreach(['White','Cream','Gold','Yellow','Pink','Purple','Wine','Red','Blue','Navy','Green','Teal','Black','Grey','Brown'] as $color): ?><label class="color-check"><input type="checkbox" name="colors[]" value="<?= $color ?>"><span><?= $color ?></span></label><?php endforeach; ?></div></div>
<div><label class="text-sm font-bold">Measurement Type *</label><div class="grid sm:grid-cols-2 gap-3 mt-2"><label class="cursor-pointer"><input class="peer sr-only" type="radio" name="measurement" value="yard" checked><span class="block rounded-2xl border border-slate-200 p-4 peer-checked:border-amber-500 peer-checked:bg-amber-50"><b>Per yard</b><small class="block text-slate-500 mt-1">36 inches</small></span></label><label class="cursor-pointer"><input class="peer sr-only" type="radio" name="measurement" value="trouser_length"><span class="block rounded-2xl border border-slate-200 p-4 peer-checked:border-amber-500 peer-checked:bg-amber-50"><b>Per trouser length</b><small class="block text-slate-500 mt-1">45 inches</small></span></label></div></div>
<div><label class="text-sm font-bold">Quantity *</label><input id="quantity" class="input mt-2" type="number" name="quantity" min="0.5" step="0.5" value="1" required></div>
<div class="grid sm:grid-cols-2 gap-4"><div><label class="text-sm font-bold">Full name *</label><input class="input mt-2" name="fullname" required></div><div><label class="text-sm font-bold">Phone number *</label><input class="input mt-2" name="phone" inputmode="tel" required></div></div><div><label class="text-sm font-bold">Location *</label><input class="input mt-2" name="location" placeholder="Town / city / delivery location" required></div><div><label class="text-sm font-bold">Order description</label><textarea class="input mt-2" name="description" rows="3" placeholder="Tell us any preferred colour shade, delivery note, or other details."></textarea></div><input class="hidden" name="website" tabindex="-1" autocomplete="off"></div>
<div class="rounded-3xl bg-benaki-navy text-white p-6 h-fit lg:sticky lg:top-4"><p class="text-xs uppercase tracking-[.2em] text-amber-300 font-bold">Live estimate</p><div class="mt-6 space-y-4 text-sm"><div class="flex justify-between gap-4"><span class="text-white/60">Fabric</span><b id="summaryFabric">—</b></div><div class="flex justify-between gap-4"><span class="text-white/60">Measurement</span><b id="summaryMeasurement" class="text-right">—</b></div><div class="flex justify-between gap-4"><span class="text-white/60">Quantity</span><b id="summaryQty">—</b></div><div class="flex justify-between gap-4"><span class="text-white/60">Price / unit</span><b id="unitPrice">₦0</b></div></div><div class="border-t border-white/10 mt-6 pt-6"><p class="text-white/60 text-sm">Estimated total</p><p id="summaryTotal" class="text-4xl font-black text-amber-300 mt-1">₦0</p><p id="lineTotal" class="text-xs text-white/40 mt-2">₦0</p></div><button id="orderSubmit" class="btn-gold mt-7 rounded-xl w-full py-4 font-black">Submit Order Request <span>→</span></button><p class="text-[11px] text-white/45 mt-4">Final availability, delivery and gift eligibility will be confirmed by our team.</p></div></div></form>
<div id="orderSuccess" class="hidden p-10 text-center"><div class="mx-auto w-20 h-20 rounded-full bg-emerald-100 text-emerald-700 grid place-items-center text-4xl">✓</div><h3 class="text-3xl font-black text-benaki-navy mt-5">Thank you for your patronage!</h3><p class="text-slate-600 mt-3 max-w-xl mx-auto">Your order request has been received. The Benaki Fabrics team will contact you soon to confirm your fabric, quantity, availability, delivery and anniversary gift details.</p><p id="orderSuccessRef" class="mt-5 font-bold text-benaki-navy"></p><p id="orderSuccessTotal" class="text-amber-700 font-extrabold mt-1"></p><button id="newOrder" class="mt-7 rounded-full border border-slate-200 px-6 py-3 font-bold">Place another order</button></div>
</div></div>

<script src="assets/js/app.js"></script>
</body>
</html>
