<?php
declare(strict_types=1);
if(session_status()!==PHP_SESSION_ACTIVE){session_name('BENAKI_ADMIN');session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'),'httponly'=>true,'samesite'=>'Lax']);session_start();}
require_once __DIR__.'/../config/db.php'; $config=require_once __DIR__.'/../config/config.php';
header_remove('X-Powered-By'); header('X-Content-Type-Options:nosniff');header('X-Frame-Options:SAMEORIGIN');header('Referrer-Policy:strict-origin-when-cross-origin');header("Content-Security-Policy:default-src 'self' https://cdn.tailwindcss.com; img-src 'self' data:; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; connect-src 'self'; frame-ancestors 'self'; base-uri 'self'; form-action 'self'");
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function redirect_to(string $p):never{header('Location:'.$p);exit;} function is_post():bool{return ($_SERVER['REQUEST_METHOD']??'GET')==='POST';}
function csrf_token():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];} function verify_csrf(?string $t):void{if(!$t||empty($_SESSION['csrf'])||!hash_equals($_SESSION['csrf'],$t)){http_response_code(419);exit('Invalid security token.');}}
function flash(string $type,string $msg):void{$_SESSION['flash'][]=[$type,$msg];}function flashes():array{$x=$_SESSION['flash']??[];unset($_SESSION['flash']);return $x;}
function logged():bool{return !empty($_SESSION['admin_id']);} function require_admin():void{if(!logged())redirect_to('login.php');} function money($n):string{return '₦'.number_format((float)$n,2);}
function json_response(bool $ok,string $message,array $extra=[]):never{header('Content-Type:application/json; charset=utf-8');echo json_encode(array_merge(['ok'=>$ok,'message'=>$message],$extra),JSON_UNESCAPED_UNICODE);exit;}
function upload_image(string $field,string $folder):?string{global $config;if(empty($_FILES[$field])||$_FILES[$field]['error']===UPLOAD_ERR_NO_FILE)return null;if($_FILES[$field]['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Image upload failed.');$max=(int)($config['app']['upload_max_bytes']??5242880);if((int)$_FILES[$field]['size']>$max)throw new RuntimeException('Image must be 5MB or smaller.');$tmp=$_FILES[$field]['tmp_name'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allowed[$mime])||@getimagesize($tmp)===false)throw new RuntimeException('Only valid JPG, PNG or WEBP images are allowed.');$name=bin2hex(random_bytes(18)).'.'.$allowed[$mime];$relative='assets/uploads/'.$folder.'/'.$name;$target=dirname(__DIR__).'/'.$relative;if(!is_dir(dirname($target)))mkdir(dirname($target),0755,true);if(!move_uploaded_file($tmp,$target))throw new RuntimeException('Could not save the image.');return $relative;}
function delete_upload(?string $path):void{if(!$path||!str_starts_with($path,'assets/uploads/'))return;$file=dirname(__DIR__).'/'.$path;if(is_file($file))@unlink($file);}
if(logged()){if(time()-(int)($_SESSION['last_activity']??time())>1800){$_SESSION=[];session_destroy();redirect_to('login.php?expired=1');}$_SESSION['last_activity']=time();}
