<?php
declare(strict_types=1); require __DIR__.'/_bootstrap.php';
if(logged()) redirect_to('index.php');
$error=''; $expired=isset($_GET['expired']);
if(is_post()){verify_csrf($_POST['csrf']??'');$u=trim((string)($_POST['username']??''));$p=(string)($_POST['password']??'');$ip=$_SERVER['REMOTE_ADDR']??'unknown';
 $s=$pdo->prepare('SELECT COUNT(*) FROM admin_login_attempts WHERE ip_address=? AND attempted_at >= (NOW() - INTERVAL 15 MINUTE) AND success=0');$s->execute([$ip]);
 if((int)$s->fetchColumn()>=8){$error='Too many failed attempts. Please wait 15 minutes.';}else{$s=$pdo->prepare('SELECT id,username,password_hash FROM admin_users WHERE username=? AND is_active=1 LIMIT 1');$s->execute([$u]);$admin=$s->fetch();$ok=$admin&&password_verify($p,$admin['password_hash']);$s=$pdo->prepare('INSERT INTO admin_login_attempts(ip_address,username,success) VALUES(?,?,?)');$s->execute([$ip,$u,$ok?1:0]);if($ok){session_regenerate_id(true);$_SESSION['admin_id']=(int)$admin['id'];$_SESSION['admin_username']=$admin['username'];$_SESSION['last_activity']=time();$pdo->prepare('UPDATE admin_users SET last_login_at=NOW() WHERE id=?')->execute([(int)$admin['id']]);redirect_to('index.php');}$error='Invalid username or password.';}}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login | Benaki Fabrics</title><link rel="stylesheet" href="assets/css/admin.css"></head><body class="login-page"><div class="login-card"><a class="brand" href="../index.php"><img src="../assets/img/benaki-logo.jpg" alt=""><span><strong>BENAKI FABRICS</strong><small>Finest Quality Textiles</small></span></a><h1>Admin Console</h1><p>Sign in to manage your store.</p><?php if($expired): ?><div class="flash error">Your session expired. Please sign in again.</div><?php endif;?><?php if($error): ?><div class="flash error"><?= e($error) ?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="field"><label>Username</label><input name="username" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn btn-dark" style="width:100%">Sign in securely</button></form><p style="margin-top:18px"><a href="../index.php">← Back to store</a></p></div></body></html>
